spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

spring.application.name=platzi-play
server.servlet.context-path=/platzi-play/api
spring.main.allow-bean-definition-overriding=true

#PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

#LangChain4j
langchain4j.google-ai-gemini.chat-model.model-name=gemini-1.5-pro
GOOGLE_API_KEY=AIzaSyCmFqddmJKoItpnX4UBQdRGFhbjNZCmcuk
