langchain4j.google-ai-gemini.chat-model.api-key=AIzaSyCmFqddmJKoItpnX4UBQdRGFhbjNZCmcuk
langchain4j.open-ai.chat-model.log-requests=true
langchain4j.open-ai.chat-model.log-responses=true
logging.level.dev.langchain4j=DEBUG
logging.level.dev.ai4j.openai4j=DEBUG
